//
//  StringExtension.swift
//  MetaX
//
//  Created by Ckitakishi on 2018/4/20.
//  Copyright © 2018 Yuhan Chen. All rights reserved.
//

// Type-safe localization symbols are now auto-generated by Xcode
// from Localizable.xcstrings (Build Setting: Generate String Catalog Symbols).
//
// Usage:
//   String(localized: .viewAllPhotos)
//   String(localized: .alertConfirm)
